### ISSUE TITLE
请问如何注入日服

### ISSUE THREAD

**Issue by yemoyu123** [hexstr/BlueArchive_SimplifiedChinese#1]
有无教程

**Comment by hexstr** [comment]
需要magisk并启用zygisk

**Comment by ywxhqwq** [comment]
> 需要magisk并启用zygisk

抱歉，我是真的没搞明白日服怎么使用，下载的包似乎也不能作为magisk模块使用，如果方便的话是否可以详细说说怎么使用呢？

**Comment by hexstr** [comment]
> > 需要magisk并启用zygisk
> 
> 抱歉，我是真的没搞明白日服怎么使用，下载的包似乎也不能作为magisk模块使用，如果方便的话是否可以详细说说怎么使用呢？

抱歉，日服的模块没写也不准备写了，我日服的账号已经无了
